//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public int BeneficiaryId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int AccountNum { get; set; }
        public string Email { get; set; }
        public int Amount { get; set; }
        public string Phone { get; set; }
        public int CustomerId { get; set; }
    }
}
