//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Detail
    {
        public int TransactionId { get; set; }
        public System.DateTime Time { get; set; }
        public string Remarks { get; set; }
        public string Mode { get; set; }
        public int Amount { get; set; }
        public int CustomerId { get; set; }
    }
}
